### ISSUE TITLE
Can't destroy an unused room?

### ISSUE THREAD

**Issue by UnConundrum** [ananace/ruby-matrix-sdk#10]
I have a room which I can find by client.find_room(id).  I left the room via the Riot desktop interface.  Now a room.leave results in 

`MatrixSdk::MatrixNotFoundError: Not a known room` 

however room.members returns my one user (details removed)

` [0] #<MatrixSdk::User:0x00007fd2a7af6ac8 @id="@user:my.homeserver.com" @display_name="user" @avatar_url=nil}>`

 api.forget_room(room.id) responds with an unrecognized access token.  Passing the access token as a parameter doesn't help.  

Initially, I set an alias for the room.  Trying to reuse the alias called the issue to my attention. 
 api.get_room_id("#user_reminders:my.homeserver.com") properly returns the room id and the server.

I feel I'm missing something.  Any ideas?

**Comment by ananace** [comment]
There's a slight issue with completely leaving rooms in Matrix, as the moment all your clients leave a room, then your server is no longer authorized to send or receive updates for the room - so old data might remain in the cache.  
Alias mappings tend to remain, as leaving doesn't destroy any data from a room - and additionally aliases require permissions to remove them.

Though the issue with `Api#forget_room` does sound like something's broken, I'll have a look at that.

If you can still join the room - and you want to reclaim the alias, I'd recommend rejoining it, removing the alias, and then leaving again. If that's not possible then it might be possible to use the [admin API for purging the room](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_room.md), or perhaps removing it from the room directory in the database. Though I'm not going to be of much help in that regard, I've not had to do any such action myself.

**Comment by UnConundrum** [comment]
Thanks for the quick response :)

Unfortunately, I was not able to rejoin the room.

I was able to remove the database records using sqlite

Thanks a bunch.

**Comment by ananace** [comment]
Well, I've been digging about in the code, and I can't find anything that could cause an access token error, so I have to assume that it's Synapse's way of describing the error condition when the room is half existing and lacking in permissions.

If you run into that particular error again I'd love if you could enable debugging (`MatrixSdk.debug!`) and post the corresponding debug output from attempting to forget the room. But for now I'll close the issue.

**Comment by UnConundrum** [comment]
Like this?


[5] pry(main)> room = Riot.new_room("<my_user_name>")
DEBUG  MatrixSdk::Api : > Sending a POST request to `/_matrix/client/r0/login`:
DEBUG  MatrixSdk::Api : > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG  MatrixSdk::Api : > accept: application/json
DEBUG  MatrixSdk::Api : > user-agent: Ruby Matrix SDK v2.0.1
DEBUG  MatrixSdk::Api : > content-type: application/json
DEBUG  MatrixSdk::Api : > content-length: 143
DEBUG  MatrixSdk::Api : >
DEBUG  MatrixSdk::Api : > {"type"=>"m.login.password", "initial_device_display_name"=>"Ruby Matrix SDK v2.0.1", "user"=>"@suser:matrix.<my_server_name>.com", "password"=>"[ REDACTED ]"}
DEBUG  MatrixSdk::Api : < Received a 200 OK response:
DEBUG  MatrixSdk::Api : < server: nginx/1.15.9 (Ubuntu)
DEBUG  MatrixSdk::Api : < date: Mon, 18 May 2020 11:35:02 GMT
DEBUG  MatrixSdk::Api : < content-type: application/json
DEBUG  MatrixSdk::Api : < content-length: 418
DEBUG  MatrixSdk::Api : < connection: keep-alive
DEBUG  MatrixSdk::Api : < cache-control: no-cache, no-store, must-revalidate
DEBUG  MatrixSdk::Api : < access-control-allow-origin: *
DEBUG  MatrixSdk::Api : < access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
DEBUG  MatrixSdk::Api : < access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
DEBUG  MatrixSdk::Api : < strict-transport-security: max-age=31536000; includeSubDomains
DEBUG  MatrixSdk::Api : < x-my-message: I have been redirected by nextcloud 443
DEBUG  MatrixSdk::Api : < front-end-https: on
DEBUG  MatrixSdk::Api : <
DEBUG  MatrixSdk::Api : < {"user_id"=>"@suser:matrix.<my_server_name>.com", "access_token"=>"[ REDACTED ]", "home_server"=>"matrix.<my_server_name>.com", "device_id"=>"BWIXKSOBGY"}
DEBUG  MatrixSdk::Api : > Sending a GET request to `/_matrix/client/r0/sync?filter=%7B%22room%22%3A%7B%22timeline%22%3A%7B%22limit%22%3A20%7D%2C%22state%22%3A%7B%22lazy_load_members%22%3Atrue%7D%7D%7D&full_state=false&timeout=15000`:
DEBUG  MatrixSdk::Api : > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG  MatrixSdk::Api : > accept: application/json
DEBUG  MatrixSdk::Api : > user-agent: Ruby Matrix SDK v2.0.1
DEBUG  MatrixSdk::Api : > authorization: [ REDACTED ]
DEBUG  MatrixSdk::Api : >
DEBUG  MatrixSdk::Api : < Received a 200 OK response:
DEBUG  MatrixSdk::Api : < server: nginx/1.15.9 (Ubuntu)
DEBUG  MatrixSdk::Api : < date: Mon, 18 May 2020 11:35:02 GMT
DEBUG  MatrixSdk::Api : < content-type: application/json
DEBUG  MatrixSdk::Api : < content-length: 59475
DEBUG  MatrixSdk::Api : < connection: keep-alive
DEBUG  MatrixSdk::Api : < cache-control: no-cache, no-store, must-revalidate
DEBUG  MatrixSdk::Api : < access-control-allow-origin: *
DEBUG  MatrixSdk::Api : < access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
DEBUG  MatrixSdk::Api : < access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
DEBUG  MatrixSdk::Api : < strict-transport-security: max-age=31536000; includeSubDomains
DEBUG  MatrixSdk::Api : < x-my-message: I have been redirected by nextcloud 443
DEBUG  MatrixSdk::Api : < front-end-https: on
DEBUG  MatrixSdk::Api : <
DEBUG  MatrixSdk::Api : < {"account_data"=>{"events"=>[{"type"=>"m.secret_storage.default_key", "content"=>{"key"=>"OHGe8JwZTmLj3wPow3n0NyUGWR7cJNvt"}}, {"type"=>"m.megolm_backup.v1", "content"=>{"encrypted"=>{"OHGe8JwZTmLj3wPo... [truncated, 59469 Bytes]
DEBUG  MatrixSdk::Room : Created room !ARfCqimkOcjxPeLmkV:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !EsyhGMozgNBrsInIFg:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !JqsmOveryRmHgnEGPB:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !LFnkLSAtbMOfzvISGJ:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !OQCVGQzAfZeTWCpjNC:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !QkLhsUXWqRjAmtkPUu:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !YzjjavoRTmpusnmYge:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !ZqfVAcztUVcsqqIOmD:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !cDPEIuoiEzPqxuZWpI:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !eBpEdyPHlUZGLEOIwI:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !iJrdZlnsajgQtgJrbn:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !iiBCytyuFgmrXMgRXP:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !jPeniegWzWYihOEtPM:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !nbGDBCjrxqOwPpFMqe:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !oGvmbwSJaFdHXqiVgL:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !oTCDAtxbDxIPnpWhDF:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !oeXouxXLdWWpZipEGj:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !pAuEyWOxNcjsVkfOYr:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !pWEPGVIIJyWigCNZOf:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !tdBHWuiIqOgRjRFFBW:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Room : Created room !zXzDZPKyhLvylMjHQJ:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Api : > Sending a POST request to `/_matrix/client/r0/createRoom`:
DEBUG  MatrixSdk::Api : > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG  MatrixSdk::Api : > accept: application/json
DEBUG  MatrixSdk::Api : > user-agent: Ruby Matrix SDK v2.0.1
DEBUG  MatrixSdk::Api : > content-type: application/json
DEBUG  MatrixSdk::Api : > content-length: 41
DEBUG  MatrixSdk::Api : > authorization: [ REDACTED ]
DEBUG  MatrixSdk::Api : >
DEBUG  MatrixSdk::Api : > {"visibility"=>"public", "room_alias"=>nil}
DEBUG  MatrixSdk::Api : < Received a 200 OK response:
DEBUG  MatrixSdk::Api : < server: nginx/1.15.9 (Ubuntu)
DEBUG  MatrixSdk::Api : < date: Mon, 18 May 2020 11:35:04 GMT
DEBUG  MatrixSdk::Api : < content-type: application/json
DEBUG  MatrixSdk::Api : < content-length: 55
DEBUG  MatrixSdk::Api : < connection: keep-alive
DEBUG  MatrixSdk::Api : < cache-control: no-cache, no-store, must-revalidate
DEBUG  MatrixSdk::Api : < access-control-allow-origin: *
DEBUG  MatrixSdk::Api : < access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
DEBUG  MatrixSdk::Api : < access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
DEBUG  MatrixSdk::Api : < strict-transport-security: max-age=31536000; includeSubDomains
DEBUG  MatrixSdk::Api : < x-my-message: I have been redirected by nextcloud 443
DEBUG  MatrixSdk::Api : < front-end-https: on
DEBUG  MatrixSdk::Api : <
DEBUG  MatrixSdk::Api : < {"room_id"=>"!SyGGKaslNTMgcStpvS:matrix.<my_server_name>.com"}
DEBUG  MatrixSdk::Room : Created room !SyGGKaslNTMgcStpvS:matrix.<my_server_name>.com
DEBUG  MatrixSdk::Api : > Sending a PUT request to `/_matrix/client/r0/directory/room/%23<my_user_name>_reminders%3Amatrix.<my_server_name>.com`:
DEBUG  MatrixSdk::Api : > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG  MatrixSdk::Api : > accept: application/json
DEBUG  MatrixSdk::Api : > user-agent: Ruby Matrix SDK v2.0.1
DEBUG  MatrixSdk::Api : > content-type: application/json
DEBUG  MatrixSdk::Api : > content-length: 54
DEBUG  MatrixSdk::Api : > authorization: [ REDACTED ]
DEBUG  MatrixSdk::Api : >
DEBUG  MatrixSdk::Api : > {"room_id"=>"!SyGGKaslNTMgcStpvS:matrix.<my_server_name>.com"}
DEBUG  MatrixSdk::Api : < Received a 409 Conflict response:
DEBUG  MatrixSdk::Api : < server: nginx/1.15.9 (Ubuntu)
DEBUG  MatrixSdk::Api : < date: Mon, 18 May 2020 11:35:04 GMT
DEBUG  MatrixSdk::Api : < content-type: application/json
DEBUG  MatrixSdk::Api : < content-length: 99
DEBUG  MatrixSdk::Api : < connection: keep-alive
DEBUG  MatrixSdk::Api : < cache-control: no-cache, no-store, must-revalidate
DEBUG  MatrixSdk::Api : < access-control-allow-origin: *
DEBUG  MatrixSdk::Api : < access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
DEBUG  MatrixSdk::Api : < access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
DEBUG  MatrixSdk::Api : < strict-transport-security: max-age=31536000; includeSubDomains
DEBUG  MatrixSdk::Api : < x-my-message: I have been redirected by nextcloud 443
DEBUG  MatrixSdk::Api : <
DEBUG  MatrixSdk::Api : < {"errcode"=>"M_UNKNOWN", "error"=>"Room alias #<my_user_name>_reminders:matrix.<my_server_name>.com already exists"}
MatrixSdk::MatrixConflictError: Room alias #<my_user_name>_reminders:matrix.<my_server_name>.com already exists
from /Users/<my_user_name>/.rvm/gems/ruby-2.6.4@v6/gems/matrix_sdk-2.0.1/lib/matrix_sdk/api.rb:302:in `block in request'


[6] pry(main)> api = Riot.api
#<MatrixSdk::Api:0x00007f8b2ceb2e90 @homeserver=#<URI::HTTPS https://matrix.<my_server_name>.com> @proxy_uri=nil @connection_address=nil @connection_port=nil @device_id=nil @autoretry=true @validate_certificate=false @transaction_id=0 @backoff_time=5000 @open_timeout=60 @read_timeout=240 @well_known={} @global_headers={"accept"=>"application/json", "user-agent"=>"Ruby Matrix SDK v2.0.1"} @http=nil}>


[7] pry(main)> api.forget_room("#<my_user_name>_reminders:matrix.<my_server_name>.")
DEBUG  MatrixSdk::Api : > Sending a POST request to `/_matrix/client/r0/rooms/%23<my_user_name>_reminders%3Amatrix.<my_server_name>./forget`:
DEBUG  MatrixSdk::Api : > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG  MatrixSdk::Api : > accept: application/json
DEBUG  MatrixSdk::Api : > user-agent: Ruby Matrix SDK v2.0.1
DEBUG  MatrixSdk::Api : > authorization: [ REDACTED ]
DEBUG  MatrixSdk::Api : >
DEBUG  MatrixSdk::Api : < Received a 401 Unauthorized response:
DEBUG  MatrixSdk::Api : < server: nginx/1.15.9 (Ubuntu)
DEBUG  MatrixSdk::Api : < date: Mon, 18 May 2020 11:36:58 GMT
DEBUG  MatrixSdk::Api : < content-type: application/json
DEBUG  MatrixSdk::Api : < content-length: 85
DEBUG  MatrixSdk::Api : < connection: keep-alive
DEBUG  MatrixSdk::Api : < cache-control: no-cache, no-store, must-revalidate
DEBUG  MatrixSdk::Api : < access-control-allow-origin: *
DEBUG  MatrixSdk::Api : < access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
DEBUG  MatrixSdk::Api : < access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
DEBUG  MatrixSdk::Api : < strict-transport-security: max-age=31536000; includeSubDomains
DEBUG  MatrixSdk::Api : < x-my-message: I have been redirected by nextcloud 443
DEBUG  MatrixSdk::Api : <
DEBUG  MatrixSdk::Api : < {"errcode"=>"M_UNKNOWN_TOKEN", "error"=>"Unrecognised access token", "soft_logout"=>false}
MatrixSdk::MatrixNotAuthorizedError: Unrecognised access token
from /Users/<my_user_name>/.rvm/gems/ruby-2.6.4@v6/gems/matrix_sdk-2.0.1/lib/matrix_sdk/api.rb:302:in `block in request'

**Comment by ananace** [comment]
I'd love if you could include a `api.whoami?` as well, just to verify that the access token is valid - right before it's considered not. But it does seem like there's very possibly a Synapse bug in this case.

Apart from that, I should note that the [forget room API call](https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-rooms-roomid-forget) needs a room ID, not a room alias.

I've tried to avoid doing too much validation in the raw API, though I might have to start adding some of those for the cases where aliases and IDs are required, it's not very obvious what you need to use in many of the cases.

**Comment by UnConundrum** [comment]
api.whoami? Returns the same access token error.

Also, trying to change a room from public to invite generates an error:

[31] pry(main)> room.invite_only= :invite
NoMethodError: undefined method `set_join_rule' for #<MatrixSdk::Api:0x00007f8aadeba340>
Did you mean?  set_room_join_rules
from /Users/<my_user_name>/.rvm/gems/ruby-2.6.4@v6/gems/matrix_sdk-2.0.1/lib/matrix_sdk/room.rb:593:in `join_rule=‘

So I tried api.set_room_join_rules(room.id, :invite) which gets the access token error


[29] pry(main)> api.set_room_join_rules(room.id, :invite)
DEBUG  MatrixSdk::Api : > Sending a PUT request to `/_matrix/client/r0/rooms/%21zXzDZPKyhLvylMjHQJ%3A<my_server_name>/state/m.room.join_rules`:
DEBUG  MatrixSdk::Api : > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG  MatrixSdk::Api : > accept: application/json
DEBUG  MatrixSdk::Api : > user-agent: Ruby Matrix SDK v2.0.1
DEBUG  MatrixSdk::Api : > content-type: application/json
DEBUG  MatrixSdk::Api : > content-length: 22
DEBUG  MatrixSdk::Api : > authorization: [ REDACTED ]
DEBUG  MatrixSdk::Api : >
DEBUG  MatrixSdk::Api : > {"join_rule"=>"invite"}
DEBUG  MatrixSdk::Api : < Received a 401 Unauthorized response:
DEBUG  MatrixSdk::Api : < server: nginx/1.15.9 (Ubuntu)
DEBUG  MatrixSdk::Api : < date: Mon, 18 May 2020 12:29:20 GMT
DEBUG  MatrixSdk::Api : < content-type: application/json
DEBUG  MatrixSdk::Api : < content-length: 85
DEBUG  MatrixSdk::Api : < connection: keep-alive
DEBUG  MatrixSdk::Api : < cache-control: no-cache, no-store, must-revalidate
DEBUG  MatrixSdk::Api : < access-control-allow-origin: *
DEBUG  MatrixSdk::Api : < access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
DEBUG  MatrixSdk::Api : < access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
DEBUG  MatrixSdk::Api : < strict-transport-security: max-age=31536000; includeSubDomains
DEBUG  MatrixSdk::Api : < x-my-message: I have been redirected by matrix 443
DEBUG  MatrixSdk::Api : <
DEBUG  MatrixSdk::Api : < {"errcode"=>"M_UNKNOWN_TOKEN", "error"=>"Unrecognised access token", "soft_logout"=>false}
MatrixSdk::MatrixNotAuthorizedError: Unrecognised access token
from /Users/<my_user_name>/.rvm/gems/ruby-2.6.4@v6/gems/matrix_sdk-2.0.1/lib/matrix_sdk/api.rb:302:in `block in request'

**Comment by ananace** [comment]
Well, if `whoami?` doesn't work, then the access token is almost definitely broken.
I'd suggest checking that `api.access_token` is correct. (Don't post it though, it's the access token after all)

**Comment by UnConundrum** [comment]
Thanks a bunch.  That was it.  Last few characters were different for some reason….
