### ISSUE TITLE
Arity Error on MatrixSdk::Client.new - ArgumentError (wrong number of arguments (given 2, expected 1))

### ISSUE THREAD

**Issue by mistergibson** [ananace/ruby-matrix-sdk#12]
MatrixSdk::Client.new("https://some.server.org",:all,{:user_id => "someuser"})
Traceback (most recent call last):
        7: from /usr/bin/irb:13:in `<main>'
        6: from org/jruby/RubyKernel.java:1189:in `catch'
        5: from org/jruby/RubyKernel.java:1189:in `catch'
        4: from org/jruby/RubyKernel.java:1442:in `loop'
        3: from org/jruby/RubyKernel.java:1048:in `eval'
        2: from (irb):3:in `evaluate'
        1: from /opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:3:in `initialize'
ArgumentError (wrong number of arguments (given 2, expected 1))

**Comment by ananace** [comment]
The method only takes a single positional argument, the homeserver URL. All the other possible arguments that can be passed to it are so-called named arguments, meaning symbol to value hashes.

What you would want to do in your case is;
```ruby
MatrixSdk::Client.new("https://some.server.org", client_cache: :all, user_id: "someuser")
```
