### ISSUE TITLE
`Client#mxid` returns String instead of MXID after `Client#login`

### ISSUE THREAD

**Issue by johannes-krude** [ananace/ruby-matrix-sdk#18]
According to the [docs](https://ruby-sdk.ananace.dev/MatrixSdk/Client.html#mxid-instance_method), `Client#mxid` should return an MXID.

When using `Client#login`, `@mxid` is assigned a String in `Client#post_authenticate`.

```
require "matrix_sdk"

client = MatrixSdk::Client.new("https://server")
begin
	client.login("user", "password")
	puts client.mxid.class
ensure
	client.logout
end
```
Results in `String`.

**Comment by ananace** [comment]
Thanks for the report, clearly need to finish building out the test suites more.
