### ISSUE TITLE
`Util::Tinycache` `unless:` argument missmatch

### ISSUE THREAD

**Issue by johannes-krude** [ananace/ruby-matrix-sdk#19]
In `lib/matrix_sdk/util/tinycache.rb:103`, the proc is called with three arguments
```
unless_proc&.call(self, method_name, args)
```
, but the proc created in `vi lib/matrix_sdk/room.rb:36`, only takes a single argument
```
unless: proc { |args| args.any? }
```

When calling `Room#all_members`, this results in:
```
	1: from .../.gem/ruby/2.7.0/gems/matrix_sdk-2.4.0/lib/matrix_sdk/util/tinycache.rb:103:in `block (2 levels) in build_cache_methods'
.../.gem/ruby/2.7.0/gems/matrix_sdk-2.4.0/lib/matrix_sdk/room.rb:36:in `block in <class:Room>': undefined method `any?' for #<MatrixSdk::Room:0x0000564f3dd6a780> (NoMethodError)
```

Possible solutions may be:
- Adding more arguments in `room.rb`
- Removing arguments in `tinycache.rb`
- Asking `Proc#arity` for the number of required arguments

**Comment by ananace** [comment]
That's a bit of an oops on my part, I had support for three arities written, but that code got lost during some git branch shenanigans. Thanks for the reports
