### ISSUE TITLE
Handling non spec-conformant events

### ISSUE THREAD

**Issue by johannes-krude** [ananace/ruby-matrix-sdk#23]
I managed to accidentally set the join_rule in a room to `nil`

```
{
  "content": {
    "join_rule": null
  },
  ...
  "type": "m.room.join_rules",
  ...
}
```

This now causes an exception in `Client#login`

```
.gem/ruby/2.7.0/gems/matrix_sdk-2.4.0.1/lib/matrix_sdk/room.rb:886:in `handle_room_join_rules': undefined method `to_sym' for nil:NilClass (NoMethodError)
```

ruby-matrix-sdk will crash for any user which is joined to that room. Although a `nil` join_rule is non spec-compliant, nothing prevents anybody from generating non spec-compliant events.

Element-desktop handles this much better and does not crash.

I would prefer, if ruby-matrix-sdk can not be crashed by anybody who shares a room with it.

**Comment by ananace** [comment]
I added some safety in handling state data and hash traversal, but as I want to avoid hiding errors as much as possible it's probably still possible to generate something that will cause horrible things to happen - to this SDK as well as other clients.
