### ISSUE TITLE
api.rb: uninitialized constant MatrixSdk::Api::CGI

### ISSUE THREAD

**Issue by gkaklas** [ananace/ruby-matrix-sdk#3]
When I try to send a message using the example client I get:

```
~/.gem/ruby/2.5.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:237:in `send_message_event': uninitialized constant MatrixSdk::Api::CGI (NameError)
```

I thought that adding `require 'cgi'` in `lib/matrix_sdk/api.rb` should fix the problem, but it only worked if I added it in `simple_client.rb` as well :thinking:.

**Comment by ananace** [comment]
I pushed some updates to the code, hopefully that should solve the CGI issues for you?

I've only tested this code with Ruby 2.3, so it's possible that something that's changed in the newer version as well, in which case I'll have to set up more testing environments.

**Comment by gkaklas** [comment]
It works now, thank you!

**Comment by 6wl** [comment]
I'm getting this issue too

ruby 2.5.3

require "matrix_sdk"
bot = MatrixSdk::Client.new('https://matrix.org')
bot.login("username", "password")
bot.rooms[1].reload_name!

Doing a require 'cgi' gets past NameError: uninitialized constant MatrixSdk::Api::CGI

**Comment by ananace** [comment]
Yes, sorry about this, I've not had any time to do a new release of the SDK since I fixed this issue.

I'll try and push a new version that will include the CGI fix as soon as I'm back at a proper desktop.
