### ISSUE TITLE
Net::OpenTimeout: execution expired

### ISSUE THREAD

**Issue by rolfschmidt** [ananace/ruby-matrix-sdk#33]
```
<#<Net::OpenTimeout: execution expired>

/opt/zammad/vendor/ruby-3.0.4/lib/ruby/3.0.0/net/http.rb:987:in `initialize'
/opt/zammad/vendor/ruby-3.0.4/lib/ruby/3.0.0/net/http.rb:987:in `open'
/opt/zammad/vendor/ruby-3.0.4/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
/opt/zammad/vendor/ruby-3.0.4/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
/opt/zammad/vendor/ruby-3.0.4/lib/ruby/3.0.0/net/http.rb:985:in `connect'
/opt/zammad/vendor/ruby-3.0.4/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
/opt/zammad/vendor/ruby-3.0.4/lib/ruby/3.0.0/net/http.rb:965:in `start'
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/matrix_sdk-2.8.0/lib/matrix_sdk/api.rb:441:in `http'
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/matrix_sdk-2.8.0/lib/matrix_sdk/api.rb:303:in `block in request'
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/matrix_sdk-2.8.0/lib/matrix_sdk/api.rb:294:in `loop'
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/matrix_sdk-2.8.0/lib/matrix_sdk/api.rb:294:in `request'
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/matrix_sdk-2.8.0/lib/matrix_sdk/protocols/cs.rb:1446:in `get_avatar_url'
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/matrix_sdk-2.8.0/lib/matrix_sdk/user.rb:60:in `avatar_url'
```

If your bot is requesting a lot you will easily get into this error. It can be solved by increasing the rate limit:

https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#override-ratelimiting-for-users

Alternatively this is also possible via SQL:

https://github.com/matrix-org/synapse/issues/6286#issuecomment-661773399

**Comment by ananace** [comment]
It should be noted that the Ruby SDK chooses not to try to intelligently handle any low-level communication issues, it will only handle expected application-level errors that can occur - things like the Matrix server responding with a 429 Too Many Requests.

If you're seeing errors with the socket not opening within the timeout, you can either expand said value
```ruby
api.open_timeout = 120
```
or use Ruby's exception handling to retry the action that failed.
