### ISSUE TITLE
This rubygem does not have a description or summary

### ISSUE THREAD

**Issue by benningm** [ananace/ruby-matrix-sdk#5]
The gem should have a summary and description in the gemspec.

Otherwise no one will find it on the rubygem archive between all those mathemtical matrix modules.

**Comment by ananace** [comment]
You are absolutely correct of course, I just stuffed a pair of empty strings in there to get rid of the bundler warnings when I started writing it - and then promptly forgot about it.

I've written up a quick summary, though it won't appear on rubygems until the next release, which I'm planning on doing as soon as I've merged the protocol split branch I've been working on.

**Comment by benningm** [comment]
Merci!
