### ISSUE TITLE
Logger issue

### ISSUE THREAD

**Issue by johan-smits** [ananace/ruby-matrix-sdk#8]
I try to add it into a Rails project but I get an error:

```ruby
client.login 'user', 'password'
NoMethodError: undefined method `[]' for #<ActiveSupport::Logger:0x00005626f02a1850>
from vendor/bundle/ruby/2.5.0/gems/matrix_sdk-1.2.1/lib/matrix_sdk/extensions.rb:76:in `logger'
Caused by NoMethodError: undefined method `[]' for #<ActiveSupport::Logger:0x00005626f02a1850>
from vendor/bundle/ruby/2.5.0/gems/matrix_sdk-1.2.1/lib/matrix_sdk/extensions.rb:76:in `logger'
```

Any suggestion on this on howto use the Rails logger?

**Comment by ananace** [comment]
Interesting, I'll try and have a look at this.  
I've used the SDK in plugins for other Rails projects before after all, and it's worked fine without any extra code/config there;
https://github.com/ananace/foreman_notification_send

**Comment by johan-smits** [comment]
But here you find any logger and not specific the Rails.logger. Did not investigate it that much yet (just tried to to a quick check) but it seemed strange that's why I opened the issue.

https://github.com/ananace/ruby-matrix-sdk/blob/9e0819c88b1332b8052dea59919af3f1a1dc4aaa/lib/matrix_sdk.rb#L37

**Comment by ananace** [comment]
I think this might be a namespace issue, where either Rails or this gem ends up importing the wrong logging extension.  
Rails and the logging gem in general tend to play very well together, so Rails should automatically reconfigure the root logger to Just Work™ without any extra changes, though the namespace issue might be getting in the way here.

I'll try to do some debugging when I have a moment of free time for that, or maybe I'll just skip having a logging extension entire and put that single-line method into all my classes directly.

**Comment by johan-smits** [comment]
Or make it configurable to pass a logging object you desire the use like this gem: [LWS](https://www.rubydoc.info/gems/lws/6.3.2#Configuration)

**Comment by ananace** [comment]
Allowing for user-specified loggers is actually a good idea, just pushed [a commit](https://github.com/ananace/ruby-matrix-sdk/commit/e381e5235b8bb2adc95f6e71663b42c4e0be269d) adding that feature.  
Though specifying the logger at a global level will currently lose the metadata of which class is logging the message, as there's no good way to store that in the logger while still allowing any valid logger implementation to be used.

It would be used like;
```ruby
cl = MatrixSdk::Client.new 'https://matrix.org'
cl.logger = <some logger instance>
```

Or;
```ruby
MatrixSdk.logger = <a global logger instance to use>
```

**Comment by johan-smits** [comment]
ActiveSupport supports  [TaggedLogging](https://api.rubyonrails.org/classes/ActiveSupport/TaggedLogging.html)

But this is very specific for ActiveSupport and that might not be what you are looking for in a generic logger.

I will try your commit and let you know the result.

**Comment by johan-smits** [comment]
It solved my issue with your commit :tada: . Looking forward to the release of it.

**Comment by ananace** [comment]
Just pushed version 1.4.0 which includes the logger method changes.

I'll have a look at a later point about a better way to replace the logger implementation, perhaps by providing a logger creation proc or something similar.
