### ISSUE TITLE
Inverted logic for SSL

### ISSUE THREAD

**Issue by kevinrademan** [ananace/ruby-matrix-sdk#9]
I found a piece of the api where the wording doesnt really make sense

```
# Check for validd ssl certificates
MatrixSdk::Client.new(url, validate_certificate: false)

# Ignore invalid ssl certificates
MatrixSdk::Client.new(url, validate_certificate: true)
```

Perhaps this flag should be changed to disable_validate_certificate?

FYI: Code at the heart of this issue
https://github.com/ananace/ruby-matrix-sdk/blob/bfa7b123fa9f11a3dd4c82ce306b5e1c76149e46/lib/matrix_sdk/api.rb#L338

**Comment by ananace** [comment]
Oh dear, seems like there's a copy-paste error in the `#verify_mode` assignment.

Would you mind throwing up a PR changing the assignment to;
```ruby
 @http.verify_mode = validate_certificate ? ::OpenSSL::SSL::VERIFY_PEER : ::OpenSSL::SSL::VERIFY_NONE
```
